[package]
name = "hazmat-macros"
version = "0.0.0"
authors = ["Jack Grigg <thestr4d@gmail.com>"]
edition = "2021"
description = "TBD"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
